### ISSUE TITLE
cannot view all certificates

### ISSUE THREAD

**Issue by iv-enovation** [manieer/moodle-block_download_certificates#1]
Hi,

I am not sure i can get the plugin to work correctly, but this might be due to my misunderstanding. I added one certificate in course c1 (certificate name "ce2"), and in course c2 a added 4 certificates, in sections:
- section 2:
  - certificate ce1
  - certificate name "ce1.1"
  - certificate name "ce1.2"
- section 3:
  - certificate name "ce2"

Now, i added a block in course c2, and it shows only one certificate, name "ce1" from course c1. all other 4 are not shown

Moodle seems having no problems with multiple certificates in one section so i believe it must be supported. As well as certificates from other courses, like in the plugin screenshots, i do not believe i can get it working as in the screenshots

**Comment by manieer** [comment]
Hi Ivan,
Thanks for you time in reviewing this plugin.

The plugin should be used on the my learning page or front page or other reports page. Using it on the actual course defeats the whole purpose of the plugin - listing issued certificates for all completed courses. Please make sure that the pdf's for the certificates have actually been issued once as the plugin directly lists these. You will also need to make sure that the 'save certificate' option is enabled for the certificate.

I have used this on our live site and all is working as expected. I had previously released this block under 'report certifcates' but due to confusions I created a new one. I did check whether I could change file names but wasn't possible on plugins directory. Here's the link to the older plugin - https://moodle.org/plugins/block_report_certificates.

Thanks,
Manir

**Comment by mudrd8mz** [comment]
> should be used on the my learning page or front page or other reports page

That is you are supposed to declare via https://docs.moodle.org/dev/Blocks/Appendix_A#applicable_formats.28.29

**Comment by iv-enovation** [comment]
I also added the to /my page and it still shows one certificate. Similarly when i click the "All My Certificates" link, it still shows only one
Do you need any further description of my setup or any screenshots, to replicate the issue?

**Comment by manieer** [comment]
Hi Ivan,
Could you check the following please?
1. Save certificates is actually set to 'YES' under certificate options.
2. The user in question has been issued a certificate i.e.. a pdf copy of the certificate has been issued for all those section 2 and section 3 courses?

Could you send me some screenshots please and I will try to replicate the issue. Also what version of moodle are you using? also which version of certificate plugin?

Thanks,
M

**Comment by manieer** [comment]
I have now added the applicable formats as suggested by David. Have done some testing and seem to be working fine at my end. But will wait to hear any feedback.

Thanks,
M

**Comment by iv-enovation** [comment]
Hi Manieer,

I think now i know what my problem was. The save option was initially set
to No, then a certificate was issued, then i changed the save option to
Yes. But Moodle thought the certificate was issued already so when i tried
to access it and this way to save the certificate, it was not re-issued and
consequently not saved

So now i believe this functionality is acceptable, but the plugin
description must be altered to clearly state that it works only with
already saved certificates. Just a question: if Moodle is OK with
re-generating a certificate that was issued but not saved, why not to
handle this situation too with your plugin?
And also: what are the unique codes there for?

I need to finish my review, there are a few checks to do. I will post my
note on the plugin page later

Best regards,
Ivan

**Comment by manieer** [comment]
Thanks Ivan. Glad its working now. The way this plugin works is if there is a pdf file stored on the system it directly pulls the file name and location so the users can download it without going into the actual course. Unfortunately the re-generating issue is with the certificate plugin which is out of my control. The unique codes are printed on the certificate so every issued certificate has a unique code on it. This can also be verified using another plugin I developed - https://moodle.org/plugins/block_verify_certificate 

I have added the relevant information under "requirement' on description page.

Thanks for your time.
Regards,
Manir

**Comment by iv-enovation** [comment]
Hi Manieer,

Where exactly is the info about that the plugin can work only with stored in the filesystem certificates? I cannot see anything in the "Requirement". My concern is that one will still expect certificates to be regenerated on request, so it must be clearly stated that only saved certificates. I do not believe that mentioned the config option is enough

Regards,
Ivan

**Comment by manieer** [comment]
Hi Ivan,
I have now added that text on the description to suggest it only works with stored pdfs (already generated certificates only). Hope this is ok.

Many thanks,
M

**Comment by iv-enovation** [comment]
Hi Manieer,
It's good now, thanks
Ivan
