### ISSUE TITLE
All My Certificate link shows the same certificates that the block

### ISSUE THREAD

**Issue by iv-enovation** [manieer/moodle-block_download_certificates#2]
It seems that the SQL query behind the page that opens with following "All My Certificates" link is the same that the SQL query behind the block itself. It is not clear so, what is the functionality of the All My Certificates page and how is it different from the block

**Comment by manieer** [comment]
Hi Ivan,
The block actually just lists the first 5 certifcates so it doesn't become too long. The second report page lists everything.

Yes you are right the sql is the same with the addition of limit on the block sql. I did look into adding this as a function on lib.php but failed to get it working (still learning). Hence I have added the way it is now.

Thanks,
Manir
