### ISSUE TITLE
String missing in language file

### ISSUE THREAD

**Issue by pierresu** [manieer/moodle-block_download_certificates#4]
I'm in the progress to customize the language files of the Download Certificates block. I stumbled upon this button text "Download all my certificates" on line 144 of the report.php file. AFAICS this string is actually not present in the en language file and therefore not translatable, except changing it in the php file itself.

**Comment by manieer** [comment]
Thanks for letting me know. I have just updated the language strings. The code has been updated on Github. I am currently testing compatibility with moodle version 3, 3.1 and 3.2. I will only push this changes to the plugin database on moodle after fully testing this.

Thanks,
M

**Comment by manieer** [comment]
I have pushed the language string changes to the Moodle plugin database. Please do review and let me have any feedback.

Kind regards,
M
